social_media_icons: true
facebook_url: "https://www.facebook.com/GEM-Website-Creator-1972669663019442/"
google_plus_url: "https://plus.google.com/114729796051510686702"
github_url: "https://github.com/emrickj/gwc"
