lang: "EN"

bootstrap_theme: true

show_navbar: true

navbar_color: default
# Color choices are default or inverse.

show_header: true
show_footer: true

social_media_icons: true

facebook_url: "https://www.facebook.com/GEM-Website-Creator-1972669663019442/"
github_url: "https://github.com/emrickj/gwc"
